SUCCESS_SIDE_EFFECT_STAGE = "success_side_effect"
SUCCESS_SIDE_EFFECT_DONE_STAGE = "success_side_effect_done"
SUCCESS_SIDE_EFFECT_STAGES = frozenset({SUCCESS_SIDE_EFFECT_STAGE, SUCCESS_SIDE_EFFECT_DONE_STAGE})
