from __future__ import annotations

import uuid
from typing import Any

from scripts.jobs import formatters
from smoke.harness import job_runtime


FlowError = job_runtime.FlowError


def build_job_payload(
    *,
    job_type: str = "job_real_llm_echo",
    model_id: str,
    input_text: str,
    instruction: str,
    client_request_id: str | None,
) -> dict[str, Any]:
    return {
        "client_request_id": client_request_id or f"smoke-llm-billing-{uuid.uuid4()}",
        "job_type": job_type,
        "job_params": {
            "model_id": model_id,
            "instruction": instruction,
            "source": {"inline": {"text": input_text}},
        },
        "metadata": {"source": f"scripts/smoke.sh {job_type}"},
        "options": {"priority": "normal", "idempotency_mode": "reject_duplicate"},
    }


def build_double_job_payload(
    *,
    model_id: str,
    input_text: str,
    first_instruction: str,
    second_instruction: str,
    client_request_id: str | None,
) -> dict[str, Any]:
    return {
        "client_request_id": client_request_id or f"smoke-llm-double-billing-{uuid.uuid4()}",
        "job_type": "job_real_llm_double_echo",
        "job_params": {
            "model_id": model_id,
            "first_instruction": first_instruction,
            "second_instruction": second_instruction,
            "source": {"inline": {"text": input_text}},
        },
        "metadata": {"source": "scripts/smoke.sh llm-job-double-billing"},
        "options": {"priority": "normal", "idempotency_mode": "reject_duplicate"},
    }


def summarize(job: dict[str, Any], billing: dict[str, Any]) -> dict[str, Any]:
    return {
        "note": "summary is generated by scripts/smoke.sh; raw HTTP envelopes are under responses",
        "job_id": job.get("job_id"),
        "job_status": job.get("job_status"),
        "model_job_type": job.get("job_type"),
        "billing_status": billing.get("status"),
        "currency": billing.get("currency"),
        "total_cost_amount": billing.get("total_cost_amount"),
        "usage_units": billing.get("usage_units"),
        "pricing_refs": billing.get("pricing_refs"),
        "ai_call_count": billing.get("ai_call_count"),
        "billable_call_count": billing.get("billable_call_count"),
        "failed_call_count": billing.get("failed_call_count"),
        "diagnostic_reason": billing.get("diagnostic_reason"),
        "finalized_at": billing.get("finalized_at"),
    }


def conclusion(job: dict[str, Any], billing: dict[str, Any]) -> str:
    return (
        f"job={job.get('job_status')} billing={billing.get('status')} "
        f"cost={billing.get('total_cost_amount')} {billing.get('currency')} "
        f"ai_call_count={billing.get('ai_call_count')}"
    )


def run(
    *,
    confirm_cost: bool,
    job_type: str = "job_real_llm_echo",
    api_url: str | None,
    model_id: str | None,
    input_text: str,
    instruction: str,
    second_instruction: str | None = None,
    caller_id: str,
    timeout_seconds: int,
    poll_interval_seconds: float,
    client_request_id: str | None,
    json_output: bool,
    allow_remote_api: bool = False,
    service_api_key: str | None = None,
    env_file: str | None = None,
) -> None:
    if not confirm_cost:
        raise FlowError("real LLM smoke scenario requires --confirm-cost", exit_code=2)
    context = job_runtime.resolve_runtime_context(
        env_file=env_file,
        api_url=api_url,
        allow_remote_api=allow_remote_api,
        caller_id=caller_id,
        service_api_key=service_api_key,
    )
    app_env = context.app_env
    selected_model = model_id or job_runtime.env_value("DEFAULT_MODEL_ID", app_env) or "gpt-5.5"
    jobs_url = str(context.summary["jobs_url"])
    headers = job_runtime.build_headers(app_env, caller_id=caller_id, service_api_key=service_api_key)

    if job_type == "job_real_llm_double_echo":
        if second_instruction is None:
            raise FlowError("second_instruction is required for double LLM smoke scenario", exit_code=2)
        payload = build_double_job_payload(
            model_id=selected_model,
            input_text=input_text,
            first_instruction=instruction,
            second_instruction=second_instruction,
            client_request_id=client_request_id,
        )
    else:
        payload = build_job_payload(
            job_type=job_type,
            model_id=selected_model,
            input_text=input_text,
            instruction=instruction,
            client_request_id=client_request_id,
        )
    create_envelope = job_runtime.request_json(jobs_url, method="POST", headers=headers, payload=payload)
    created = job_runtime.data_object(create_envelope, "job")
    job_id = str(created["job_id"])
    get_job_envelope = job_runtime.poll_job_envelope(
        jobs_url=jobs_url,
        job_id=job_id,
        headers=headers,
        timeout_seconds=timeout_seconds,
        poll_interval_seconds=poll_interval_seconds,
    )
    terminal_job = job_runtime.data_object(get_job_envelope, "job")
    billing_envelope = job_runtime.request_json(f"{jobs_url}/{job_id}/billing", method="GET", headers=headers)
    billing = job_runtime.data_object(billing_envelope, "billing")
    summary = summarize(terminal_job, billing)
    summary["context"] = context.summary
    if json_output:
        formatters.print_json(
            {
                "conclusion": conclusion(terminal_job, billing),
                "summary": summary,
                "responses": {
                    "create_job": create_envelope,
                    "get_job": get_job_envelope,
                    "get_billing": billing_envelope,
                },
            }
        )
    else:
        formatters.section("Smoke")
        formatters.event("OK", "job", f"id={job_id} status={terminal_job.get('job_status')}")
        formatters.event(
            "OK",
            "billing",
            f"status={billing.get('status')} total={billing.get('total_cost_amount')} {billing.get('currency')}",
        )
        formatters.print_table(
            [summary],
            [
                ("job_id", "job_id"),
                ("job_status", "job"),
                ("billing_status", "billing"),
                ("total_cost_amount", "cost"),
                ("currency", "currency"),
                ("usage_units", "usage"),
                ("pricing_refs", "pricing_refs"),
            ],
        )
    if terminal_job.get("job_status") != "succeeded":
        raise FlowError(f"job {job_id} finished with {terminal_job.get('job_status')}", exit_code=1)
