from __future__ import annotations

from app.integrations.image.validation import ImageValidationPolicy

POSTER_TITLE_IMAGE_REFERENCE_ALLOWED_CONTENT_TYPES = frozenset({"image/png", "image/jpeg", "image/webp"})
POSTER_TITLE_IMAGE_REFERENCE_MAX_BYTES = 20 * 1024 * 1024
POSTER_TITLE_IMAGE_REFERENCE_MAX_WIDTH = 4096
POSTER_TITLE_IMAGE_REFERENCE_MAX_HEIGHT = 4096
POSTER_TITLE_IMAGE_REFERENCE_MAX_PIXELS = 16_777_216
POSTER_TITLE_IMAGE_REFERENCE_POLICY = ImageValidationPolicy(
    allowed_content_types=POSTER_TITLE_IMAGE_REFERENCE_ALLOWED_CONTENT_TYPES,
    max_bytes=POSTER_TITLE_IMAGE_REFERENCE_MAX_BYTES,
    max_width=POSTER_TITLE_IMAGE_REFERENCE_MAX_WIDTH,
    max_height=POSTER_TITLE_IMAGE_REFERENCE_MAX_HEIGHT,
    max_pixels=POSTER_TITLE_IMAGE_REFERENCE_MAX_PIXELS,
)
