from __future__ import annotations

from pydantic import BaseModel

from app.schemas.billing import BillingEnvelope, JobBillingResponseData, ScopeBillingResponseData
from app.schemas.jobs import (
    ArithmeticParams,
    ArithmeticResult,
    ArithmeticRuntimeFields,
    CreateJobRequest,
    JobResponseData,
    JobTestAddParams,
    JobTestAddResult,
    JobTestAddRuntimeFields,
    JobTestCollectParams,
    JobTestCollectResult,
    JobTestCollectRuntimeFields,
    JobTestEchoParams,
    JobTestEchoResult,
    JobTestEchoRuntimeFields,
    JobTestWorkflowParams,
    JobTestWorkflowResult,
    JobTestWorkflowRuntimeFields,
    JobRealLlmEchoParams,
    JobRealLlmEchoResult,
    JobRealLlmEchoRuntimeFields,
    JobRealLlmDoubleEchoParams,
    JobRealLlmDoubleEchoResult,
    JobRealLlmDoubleEchoRuntimeFields,
    OssUrlRef,
    PosterTitleImageBatchSummary,
    PosterTitleImageDurationMs,
    PosterTitleImageError,
    PosterTitleImageGenerateItemParams,
    PosterTitleImageGenerateItemResult,
    PosterTitleImageGenerateItemRuntimeFields,
    PosterTitleImageImage,
    PosterTitleImageItemParams,
    PosterTitleImageJoinParams,
    PosterTitleImageJoinRuntimeFields,
    PosterTitleImageModelOptions,
    PosterTitleImageObject,
    PosterTitleImageParams,
    PosterTitleImagePromptOverrides,
    PosterTitleImageReferenceImage,
    PosterTitleImageResult,
    PosterTitleImageResultItem,
    PosterTitleImageRuntimeFields,
    PosterTitleImageStyleProbeParams,
    PosterTitleImageStyleProbeResult,
    PosterTitleImageStyleProbeRuntimeFields,
)
from app.schemas.meta import LanguagesResponse, ModelsResponse, PromptTemplateResponseData

_SCHEMAS: dict[str, type[BaseModel]] = {
    schema.__name__: schema
    for schema in (
        CreateJobRequest,
        JobResponseData,
        BillingEnvelope,
        JobBillingResponseData,
        ScopeBillingResponseData,
        ArithmeticParams,
        ArithmeticRuntimeFields,
        ArithmeticResult,
        JobTestAddParams,
        JobTestAddRuntimeFields,
        JobTestAddResult,
        JobTestCollectParams,
        JobTestCollectRuntimeFields,
        JobTestCollectResult,
        JobTestEchoParams,
        JobTestEchoRuntimeFields,
        JobTestEchoResult,
        JobTestWorkflowParams,
        JobTestWorkflowRuntimeFields,
        JobTestWorkflowResult,
        JobRealLlmEchoParams,
        JobRealLlmEchoRuntimeFields,
        JobRealLlmEchoResult,
        JobRealLlmDoubleEchoParams,
        JobRealLlmDoubleEchoRuntimeFields,
        JobRealLlmDoubleEchoResult,
        OssUrlRef,
        PosterTitleImageReferenceImage,
        PosterTitleImageModelOptions,
        PosterTitleImagePromptOverrides,
        PosterTitleImageItemParams,
        PosterTitleImageParams,
        PosterTitleImageRuntimeFields,
        PosterTitleImageStyleProbeParams,
        PosterTitleImageStyleProbeRuntimeFields,
        PosterTitleImageStyleProbeResult,
        PosterTitleImageGenerateItemParams,
        PosterTitleImageGenerateItemRuntimeFields,
        PosterTitleImageObject,
        PosterTitleImageImage,
        PosterTitleImageError,
        PosterTitleImageResultItem,
        PosterTitleImageBatchSummary,
        PosterTitleImageDurationMs,
        PosterTitleImageGenerateItemResult,
        PosterTitleImageJoinParams,
        PosterTitleImageJoinRuntimeFields,
        PosterTitleImageResult,
        ModelsResponse,
        LanguagesResponse,
        PromptTemplateResponseData,
    )
}


def get_schema(name: str) -> type[BaseModel]:
    return _SCHEMAS[name]


def all_schema_names() -> set[str]:
    return set(_SCHEMAS)
