from __future__ import annotations

from pydantic import BaseModel

from app.schemas.billing import BillingEnvelope, JobBillingResponseData, ScopeBillingResponseData
from app.schemas.jobs import (
    AudioStemSeparationDurationMs,
    AudioDecodeNormalizeRequest,
    AudioDecodeNormalizeSpec,
    AudioInputPlanSnapshot,
    AudioStemSeparationInputObject,
    CanonicalObjectRefSnapshot,
    MediaFetchSpec,
    PreparedAudioInputMetadata,
    AudioStemSeparationOutputObject,
    AudioStemSeparationParams,
    AudioStemSeparationResult,
    AudioStemSeparationRuntimeFields,
    AudioStemSeparationStemOutputs,
    AudioStemSeparationTritonParams,
    AudioStemSeparationTritonResult,
    AudioStemSeparationTritonRuntimeFields,
    ArithmeticParams,
    ArithmeticResult,
    ArithmeticRuntimeFields,
    CreateJobRequest,
    ExampleCollectParams,
    ExampleCollectResult,
    ExampleCollectRuntimeFields,
    ExamplePairParams,
    ExamplePairResult,
    ExamplePairRuntimeFields,
    ExampleSleepParams,
    ExampleSleepResult,
    ExampleSleepRuntimeFields,
    ExampleWorkflowParams,
    ExampleWorkflowResult,
    ExampleWorkflowRuntimeFields,
    JobResponseData,
    JobRealLlmEchoParams,
    JobRealLlmEchoResult,
    JobRealLlmEchoRuntimeFields,
    JobRealLlmDoubleEchoParams,
    JobRealLlmDoubleEchoResult,
    JobRealLlmDoubleEchoRuntimeFields,
    OssUrlRef,
    TaggedTextTranslationCharCount,
    TaggedTextTranslationItemParams,
    TaggedTextTranslationParams,
    TaggedTextTranslationResult,
    TaggedTextTranslationResultItem,
    TaggedTextTranslationRuntimeFields,
    PosterTitleImageBatchSummary,
    PosterTitleImageDurationMs,
    PosterTitleImageError,
    PosterTitleImageGenerateItemParams,
    PosterTitleImageGenerateItemResult,
    PosterTitleImageGenerateItemRuntimeFields,
    PosterTitleImageImage,
    PosterTitleImageItemParams,
    PosterTitleImageJoinParams,
    PosterTitleImageJoinRuntimeFields,
    PosterTitleImageModelOptions,
    PosterTitleImageObject,
    PosterTitleImageParams,
    PosterTitleImagePromptOverrides,
    PosterTitleImageReferenceImage,
    PosterTitleImageResult,
    PosterTitleImageResultItem,
    PosterTitleImageRuntimeFields,
    PosterTitleImageStyleProbeParams,
    PosterTitleImageStyleProbeResult,
    PosterTitleImageStyleProbeRuntimeFields,
    RuntimeSystemFields,
)
from app.schemas.meta import LanguagesResponse, ModelsResponse, PromptTemplateResponseData

_SCHEMAS: dict[str, type[BaseModel]] = {
    schema.__name__: schema
    for schema in (
        CreateJobRequest,
        JobResponseData,
        BillingEnvelope,
        JobBillingResponseData,
        ScopeBillingResponseData,
        ArithmeticParams,
        ArithmeticRuntimeFields,
        ArithmeticResult,
        ExamplePairParams,
        ExamplePairRuntimeFields,
        ExamplePairResult,
        ExampleCollectParams,
        ExampleCollectRuntimeFields,
        ExampleCollectResult,
        ExampleSleepParams,
        ExampleSleepRuntimeFields,
        ExampleSleepResult,
        ExampleWorkflowParams,
        ExampleWorkflowRuntimeFields,
        ExampleWorkflowResult,
        JobRealLlmEchoParams,
        JobRealLlmEchoRuntimeFields,
        JobRealLlmEchoResult,
        JobRealLlmDoubleEchoParams,
        JobRealLlmDoubleEchoRuntimeFields,
        JobRealLlmDoubleEchoResult,
        TaggedTextTranslationItemParams,
        TaggedTextTranslationParams,
        TaggedTextTranslationRuntimeFields,
        TaggedTextTranslationCharCount,
        TaggedTextTranslationResultItem,
        TaggedTextTranslationResult,
        AudioStemSeparationInputObject,
        CanonicalObjectRefSnapshot,
        MediaFetchSpec,
        AudioDecodeNormalizeSpec,
        AudioDecodeNormalizeRequest,
        AudioInputPlanSnapshot,
        PreparedAudioInputMetadata,
        AudioStemSeparationParams,
        AudioStemSeparationRuntimeFields,
        AudioStemSeparationTritonParams,
        AudioStemSeparationTritonRuntimeFields,
        AudioStemSeparationOutputObject,
        AudioStemSeparationStemOutputs,
        AudioStemSeparationDurationMs,
        AudioStemSeparationResult,
        AudioStemSeparationTritonResult,
        RuntimeSystemFields,
        OssUrlRef,
        PosterTitleImageReferenceImage,
        PosterTitleImageModelOptions,
        PosterTitleImagePromptOverrides,
        PosterTitleImageItemParams,
        PosterTitleImageParams,
        PosterTitleImageRuntimeFields,
        PosterTitleImageStyleProbeParams,
        PosterTitleImageStyleProbeRuntimeFields,
        PosterTitleImageStyleProbeResult,
        PosterTitleImageGenerateItemParams,
        PosterTitleImageGenerateItemRuntimeFields,
        PosterTitleImageObject,
        PosterTitleImageImage,
        PosterTitleImageError,
        PosterTitleImageResultItem,
        PosterTitleImageBatchSummary,
        PosterTitleImageDurationMs,
        PosterTitleImageGenerateItemResult,
        PosterTitleImageJoinParams,
        PosterTitleImageJoinRuntimeFields,
        PosterTitleImageResult,
        ModelsResponse,
        LanguagesResponse,
        PromptTemplateResponseData,
    )
}


def get_schema(name: str) -> type[BaseModel]:
    return _SCHEMAS[name]


def all_schema_names() -> set[str]:
    return set(_SCHEMAS)
