from __future__ import annotations

import time
import uuid
from typing import Any

from smoke.flows.examples import lifecycle_probe
from smoke.harness import callback_capture
from smoke.harness import cli_contract
from smoke.harness import env_runtime
from smoke.harness import formatters
from smoke.harness import http_runtime
from smoke.harness import service_runtime
from smoke.harness.errors import FlowError
from smoke.jobs import callback as job_callback
from smoke.jobs import cli_contract as job_cli_contract
from smoke.jobs import reconciler_faults
from smoke.jobs import runtime as job_runtime


SCENARIO_NAME = "example-reconciler-probe"


def _summary(
    *,
    context_summary: dict[str, Any],
    terminal_job: dict[str, Any],
    callback_job: dict[str, Any],
    injection: reconciler_faults.CallbackGapInjection,
    callback_outbox: dict[str, Any],
    callback_waited: bool,
) -> dict[str, Any]:
    return {
        "note": "summary is generated by scripts/smoke.sh; this scenario injects a local/dev DB fault to prove reconciler recovery",
        "scenario": SCENARIO_NAME,
        "job_id": callback_job.get("job_id"),
        "job_status": callback_job.get("job_status"),
        "expected_status": injection.job_status,
        "callback_status": lifecycle_probe.callback_status(callback_job),
        "callback_attempt": lifecycle_probe.callback_attempt(callback_job),
        "callback_waited": callback_waited,
        "fault_injection": {
            "kind": "terminal_callback_outbox_missing",
            "injected_at": injection.injected_at,
            "callback_event_type": injection.callback_event_type,
            "terminal_job_status_before_injection": terminal_job.get("job_status"),
        },
        "callback_outbox": callback_outbox,
        "mechanism_evidence": {
            "api": "create-job HTTP response returned job_id without callback configured",
            "dispatcher": "job reached terminal status through dispatch_outbox -> Taskiq",
            "taskiq_worker": "job executor produced terminal result/error",
            "reconciler": "after terminal status, smoke injected callback_url with missing callback_outbox; callback_outbox appeared later",
            "callbacker": "callback.status=delivered and local callback receiver captured the signed event",
        },
        "context": context_summary,
    }


def run(
    *,
    job_options: job_cli_contract.JobSmokeOptions,
    callback_options: cli_contract.CallbackSmokeOptions,
    confirm_fault_injection: bool,
    api_url: str | None,
    env_file: str | None,
    allow_remote_api: bool,
    service_api_key: str | None,
    caller_id: str,
    timeout_seconds: int,
    poll_interval_seconds: float,
    probe_id: str,
    message: str,
    sleep_seconds: float,
    fail: bool,
    fail_after_seconds: float,
    result_payload: str | None,
    result_size_bytes: int,
    json_output: bool,
) -> None:
    if not job_options.confirm_run:
        raise FlowError("example reconciler probe smoke requires --confirm-run", exit_code=2)
    if not confirm_fault_injection:
        raise FlowError("example reconciler probe smoke requires --confirm-fault-injection", exit_code=2)
    if callback_options.callback_url is not None:
        raise FlowError("example reconciler probe requires --local-callback; --callback-url is not supported", exit_code=2)
    if not callback_options.local_callback:
        raise FlowError("example reconciler probe requires --local-callback", exit_code=2)
    if not callback_options.wait_callback:
        raise FlowError("example reconciler probe requires --wait-callback", exit_code=2)

    expected = lifecycle_probe.expected_status(fail=fail, expect_status=job_options.expect_status)
    context = job_runtime.resolve_job_context(
        env_file=env_file,
        api_url=api_url,
        allow_remote_api=allow_remote_api,
        caller_id=caller_id,
        service_api_key=service_api_key,
    )
    configured_app_env = env_runtime.env_value("APP_ENV", context.app_env) or "local"
    reconciler_faults.assert_local_fault_injection_app_env(configured_app_env)
    if not lifecycle_probe.is_loopback_api(str(context.summary["api_url"])):
        raise FlowError("example reconciler probe requires a loopback API URL", exit_code=2)
    database_url = reconciler_faults.database_url_from_app_env(context.app_env)
    database_ssl = reconciler_faults.database_ssl_from_app_env(context.app_env)

    jobs_url = str(context.summary["jobs_url"])
    headers = service_runtime.build_headers(
        context.app_env,
        caller_id=caller_id,
        service_api_key=service_api_key,
    )
    receiver_context = lifecycle_probe.local_callback_server(context)
    capture_event = None
    deadline = time.monotonic() + timeout_seconds
    try:
        with receiver_context as receiver:
            effective_callback_url = callback_options.callback_url or (receiver.url if receiver is not None else None)
            if effective_callback_url is None:
                raise FlowError("callback URL was not resolved for reconciler probe", exit_code=2)
            if callback_options.callback_event not in {"both", expected}:
                raise FlowError("--callback-event must include the expected terminal job status", exit_code=2)

            create_payload = lifecycle_probe.build_payload(
                probe_id=probe_id,
                message=message,
                sleep_seconds=sleep_seconds,
                fail=fail,
                fail_after_seconds=fail_after_seconds,
                result_payload=result_payload,
                result_size_bytes=result_size_bytes,
                callback_url=None,
                callback_event=callback_options.callback_event,
                client_request_id=job_options.client_request_id
                or f"smoke-example-reconciler-probe-{uuid.uuid4()}",
            )
            create_payload["metadata"] = {
                "source": f"scripts/smoke.sh {SCENARIO_NAME}",
                "probe_id": probe_id,
                "fault": "terminal_callback_outbox_missing",
            }
            create_envelope = http_runtime.request_json(jobs_url, method="POST", headers=headers, payload=create_payload)
            created = http_runtime.data_object(create_envelope, "job")
            job_id = str(created["job_id"])
            get_job_envelope = job_runtime.poll_job_envelope(
                jobs_url=jobs_url,
                job_id=job_id,
                headers=headers,
                timeout_seconds=lifecycle_probe.remaining_timeout_seconds(
                    deadline,
                    timeout_seconds=timeout_seconds,
                ),
                poll_interval_seconds=poll_interval_seconds,
            )
            terminal_job = http_runtime.data_object(get_job_envelope, "job")
            lifecycle_probe.assert_terminal_job(
                terminal_job,
                expected=expected,
                probe_id=probe_id,
                message=message,
                forced_failure=fail,
            )
            if lifecycle_probe.callback_status(terminal_job) != "not_configured":
                raise FlowError(
                    f"reconciler probe expected terminal job callback=not_configured before injection, got {terminal_job.get('callback')}",
                    exit_code=1,
                )

            injected_events = lifecycle_probe.callback_events(callback_options.callback_event)
            injection = reconciler_faults.inject_missing_callback_outbox(
                database_url=database_url,
                database_ssl=database_ssl,
                job_id=job_id,
                callback_url=effective_callback_url,
                callback_events=injected_events,
            )
            callback_outbox = reconciler_faults.wait_for_callback_outbox(
                database_url=database_url,
                database_ssl=database_ssl,
                job_id=job_id,
                callback_event_type=injection.callback_event_type,
                timeout_seconds=lifecycle_probe.remaining_timeout_seconds(
                    deadline,
                    timeout_seconds=timeout_seconds,
                ),
                poll_interval_seconds=poll_interval_seconds,
            )
            callback_envelope = None
            callback_job = terminal_job
            callback_waited = bool(effective_callback_url and callback_options.wait_callback)
            if callback_waited:
                callback_envelope = lifecycle_probe.poll_callback_envelope(
                    jobs_url=jobs_url,
                    job_id=job_id,
                    headers=headers,
                    timeout_seconds=lifecycle_probe.remaining_callback_timeout_seconds(
                        deadline,
                        timeout_seconds=timeout_seconds,
                        callback_timeout_seconds=callback_options.callback_timeout_seconds,
                    ),
                    poll_interval_seconds=poll_interval_seconds,
                )
                callback_job = http_runtime.data_object(callback_envelope, "job")
                callback_outbox = reconciler_faults.callback_outbox_evidence(
                    database_url=database_url,
                    database_ssl=database_ssl,
                    job_id=job_id,
                    callback_event_type=injection.callback_event_type,
                ) or callback_outbox
                if receiver is not None:
                    capture_event = receiver.wait_for_event(
                        job_callback.job_callback_expectation(
                            job_id=job_id,
                            event=f"job.{expected}",
                            job_status=expected,
                        ),
                        timeout_seconds=lifecycle_probe.remaining_callback_timeout_seconds(
                            deadline,
                            timeout_seconds=timeout_seconds,
                            callback_timeout_seconds=callback_options.callback_timeout_seconds,
                        ),
                    )

            local_callback_events = receiver.snapshot() if receiver is not None else []
            if callback_options.local_callback and callback_options.wait_callback and not local_callback_events:
                raise FlowError("local callback receiver did not capture any callback event", exit_code=1)
    except callback_capture.CallbackCaptureError as exc:
        raise FlowError(str(exc), exit_code=exc.exit_code) from exc

    summary = _summary(
        context_summary=context.summary,
        terminal_job=terminal_job,
        callback_job=callback_job,
        injection=injection,
        callback_outbox=callback_outbox,
        callback_waited=callback_waited,
    )
    if json_output:
        responses: dict[str, Any] = {"create_job": create_envelope, "get_job": get_job_envelope}
        if callback_envelope is not None:
            responses["callback_job"] = callback_envelope
        formatters.print_json(
            {
                "ok": True,
                "scenario": SCENARIO_NAME,
                "conclusion": (
                    f"job={summary['job_status']} reconciler=callback_outbox_created "
                    f"callback={summary['callback_status'] or '-'}"
                ),
                "summary": summary,
                "responses": responses,
                "local_callback": {
                    "enabled": callback_options.local_callback,
                    "url": effective_callback_url if callback_options.local_callback else None,
                    "event_count": len(local_callback_events),
                    "matched_event": capture_event,
                    "events": local_callback_events,
                },
            }
        )
        return

    formatters.section("Example Reconciler Probe")
    formatters.event("OK", "job", f"id={summary['job_id']} status={summary['job_status']} expected={expected}")
    formatters.event("OK", "reconciler", f"callback_outbox={callback_outbox['status']}")
    if effective_callback_url is not None:
        formatters.event(
            "OK" if summary["callback_status"] == "delivered" else "INFO",
            "callback",
            f"status={summary['callback_status']} attempt={summary['callback_attempt']}",
        )
    formatters.print_table(
        [summary],
        [
            ("job_id", "job_id"),
            ("job_status", "job"),
            ("expected_status", "expected"),
            ("callback_status", "callback"),
            ("callback_attempt", "attempt"),
            ("callback_waited", "waited"),
        ],
    )
